function PrintableDocument({ title, subtitle, documentNumber, date, children, onPrint }) {
  function handlePrint() {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  }

  return (
    <div className="printable-container" style={{ background: "#fff", padding: "24px", borderRadius: "var(--radius)", border: "1px solid var(--border)" }}>
      <div className="print-hide" style={{ display: "flex", justifyContent: "flex-end", marginBottom: "16px" }}>
        <button type="button" className="button button-primary" onClick={handlePrint}>
          🖨 Print Document
        </button>
      </div>

      <div className="printable-document" style={{ color: "#172033" }}>
        <div style={{ borderBottom: "2px solid #1769aa", paddingBottom: "12px", marginBottom: "20px", display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
          <div>
            <h1 style={{ margin: 0, fontSize: "20px", color: "#1769aa", fontWeight: 800 }}>
              HOSPITAL MANAGEMENT SYSTEM
            </h1>
            <p style={{ margin: "4px 0 0", fontSize: "12px", color: "#637083" }}>
              Clinical & Patient Care Operations
            </p>
          </div>
          <div style={{ textAlign: "right" }}>
            <h2 style={{ margin: 0, fontSize: "16px", fontWeight: 700 }}>{title}</h2>
            {subtitle && <p style={{ margin: "2px 0 0", fontSize: "12px", color: "#637083" }}>{subtitle}</p>}
            {documentNumber && <p style={{ margin: "2px 0 0", fontSize: "12px", fontWeight: 600 }}>Ref: {documentNumber}</p>}
            {date && <p style={{ margin: "2px 0 0", fontSize: "11px", color: "#8a96a6" }}>Date: {date}</p>}
          </div>
        </div>

        <div className="printable-content">{children}</div>

        <div style={{ marginTop: "32px", borderTop: "1px solid #dfe6ee", paddingTop: "12px", display: "flex", justifyContent: "space-between", fontSize: "11px", color: "#8a96a6" }}>
          <span>Generated by Hospital Information System</span>
          <span>Confidential Medical Document</span>
        </div>
      </div>
    </div>
  );
}

export default PrintableDocument;
